### ISSUE TITLE
[Feature]Read from command line

### ISSUE THREAD

**Issue by HHoflittlefish777** [labring/sealfs#14]
We need to read the configuration file or parameters from the control line, but now we read directly from the default configuration file

**Comment by HHoflittlefish777** [comment]
detail location：https://github.com/labring/sealfs/tree/main/src/bin

**Comment by dinoallo** [comment]
I opened a PR: https://github.com/labring/sealfs/pull/89

**Comment by dinoallo** [comment]
Also wondering, if it is a good idea to move and uniform CLI related stuff like: https://github.com/labring/sealfs/blob/9f751259c6ad777e66b862d7295fe00db7467ee5/src/client/mod.rs#L226-L238
to `src/main/bin` for cleaner file structure?
