### ISSUE TITLE
Refactor Project Structure

### ISSUE THREAD

**Issue by HHoflittlefish777** [labring/sealfs#21]
The current structure is somewhat chaotic and needs to be reconstructed

**Comment by uran0sH** [comment]
Plz elaborate on where the structure is confusing. Don't use such fuzzy language.

**Comment by HHoflittlefish777** [comment]
@luanshaotong can explain it.

**Comment by HHoflittlefish777** [comment]
Core modules need to be placed in the src directory, but now they are at the same level as src，like server,client

**Comment by uran0sH** [comment]
Core modules are not forced to place in the src folder in Rust, like image-service(https://github.com/dragonflyoss/image-service), cloud-hypervisor(https://github.com/cloud-hypervisor/cloud-hypervisor), stratovirt(https://gitee.com/openeuler/stratovirt), and so on.

**Comment by luanshaotong** [comment]
@uran0sH good examples. So it's ok to keep status quo, right?

**Comment by uran0sH** [comment]
Moving crates to src can make them share the `Cargo.toml`, which is convenient for managing dependencies. We can refactor after completing the first version if we need it.

**Comment by uran0sH** [comment]
pr: #57
