### ISSUE TITLE
Implement thread safe treemap

### ISSUE THREAD

**Issue by HHoflittlefish777** [labring/sealfs#26]
In the consistency hash module, we use rwlock+btreemap to cache data, but there are the following problems: that is, using a third-party rwlock library can only ensure fair read and write, but in this update heartbeat cache scenario, we need to write first, and the performance of rwlock+btreemap is not very good，This is an important work. If you are interested in this, you can write a tool class and put it in the common.Of course, we need to have a benchmark to reflect the performance.
在一致性hash模块中，我们用rwlock + btreemap对数据进行缓存，但是存在以下问题：即使用了第三方rwlock库也只能保证读写公平，但是在这个更新心跳缓存场景之下我们需要写优先，同时rwlock + btreemap的性能也不太好，这是一个重要的工作，如果对这个感兴趣的话，可以写一个工具类放到common中，当然，我们需要有一个基准测试来体现性能

**Comment by luanshaotong** [comment]
这个模块的实现类似于dashmap吗？

**Comment by HHoflittlefish777** [comment]
是的，但是这个基于特定的元数据缓存场景，没有比较好的第三方库可以使用，或者说不太合适，需要自己完成

**Comment by HHoflittlefish777** [comment]
The update frequency is not very high. Write priority lock is not required for the time being. Close it first.
